name: Stats
on:
  schedule:
    # Towards the end of the day for meaningful most recent data point
    - cron: "45 23 * * *"
  workflow_dispatch:

jobs:
  stats:
    name: github-repo-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - awesome-safety-tools
          - community
          - coop
          - coop-integration-example
          - osprey
          - playground
    steps:
      - name: run-ghrs
        # jgehrcke/github-repo-stats hasn't created a git tag or GitHub Release recently,
        # but instead maintains a `RELEASE` branch; this hash tracks its latest commit.
        uses: jgehrcke/github-repo-stats@d80572c9029636cd0e97e3a79e7a9c293bea3b02
        with:
          repository: roostorg/${{ matrix.repo }}
          databranch: main
          ghpagesprefix: https://roostorg.github.io/stats
          ghtoken: ${{ secrets.ghrs_github_api_token }}
